// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"web-page-analyzer/internal/api"
	"web-page-analyzer/internal/persistance"
	"web-page-analyzer/internal/process"
	"web-page-analyzer/internal/service"
	"web-page-analyzer/router"
)

// Injectors from wire.go:

func InitializeRouter() *gin.Engine {
	inMemoryStore := persistance.NewMemoryStore()
	patternExecutor := process.NewPatternExecutor()
	analyzerService := service.NewAnalyzerService(inMemoryStore, patternExecutor)
	analyzerController := api.NewAnalyzerController(analyzerService)
	engine := router.SetupRouter(analyzerController)
	return engine
}

// wire.go:

var StoreSet = wire.NewSet(persistance.NewMemoryStore, wire.Bind(new(persistance.Store), new(*persistance.InMemoryStore)))
